name: Just Try
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: node --version > node-version.txt
    - run: gcc --version > gcc-version.txt
    - run: python --version > python-version.txt
  job2:
    runs-on: windows-latest
    steps:
    - run: node --version > node-version.txt
    - run: gcc --version > gcc-version.txt
    - run: python --version > python-version.txt