name: Just Try
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: node --version
    - run: gcc --version
    - run: python --version
  job2:
    runs-on: windows-latest
    steps:
    - run: node --version
    - run: gcc --version
    - run: python --version